server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: persona-service
          uri: lb://persona-service
          predicates:
            - Path=/personas/**
        - id: imagen-service
          uri: lb://imagen-service
          predicates:
            - Path=/imagenes/**